#!/bin/sh
#
# /etc/rc.d/caddy: start/stop caddy
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/caddy
PID=/var/run/caddy.pid
OPTS="-conf=/etc/caddy/caddy.conf -agree=true -pidfile=$PID"

case $1 in
start)
	# Set the CADDYPATH; Let's Encrypt certificates will be written to this directory.
	export CADDYPATH=/etc/caddy/ssl

	# Set the ulimits
	ulimit -n 8192

	$SSD --start --background --pidfile $PID --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --retry 10 --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG is running with pid $(cat $PID)" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
